### ISSUE TITLE
Add XRPL Object types

### ISSUE THREAD

**Issue by pkcs8** [xrpscan/platform#3]
```[tasklist]
### Tasks
- [x] Add Transaction object
- [x] Add Currency object
- [x] Add Memo object
- [x] Add MetaData object
- [x] Add Path object
- [x] Add Signer object
- [x] Add SignerEntry object
```
