### ISSUE TITLE
Add support for indexing and searching by CTID

### ISSUE THREAD

**Issue by pkcs8** [xrpscan/platform#44]
```[tasklist]
### Tasks
- [ ] https://github.com/xrpscan/platform/issues/45
- [ ] https://github.com/xrpscan/platform/issues/46
- [ ] https://github.com/xrpscan/xrpl-go/issues/3
```
